[General]
CefOsrWindowlessFrameRate=30
GeoLocale=system
SensitiveInfoMaskOn=true
ShowBiDirecSyncNoti=true
autoPlayGif=false
autoScale=true
bForceMaximizeWM=false
captureHDCamera=true
cefInstanceCountLimit=-1
cefRefreshTime=0
chatListPanelLastWidth=230
com.disable.connection.pk.status=false
com.zoom.client.langid=0
conf.webserver=https://us05web.zoom.us
conf.webserver.vendor.default=https://zoom.us
currentMeetingId=96311589893
deviceID=D8:B3:2F:BD:C6:85
disableCef=false
disableUsePasskey=false
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCefGpu=false
enableCefLog=false
enableCefOsrIme=true
enableCefOsrMode=true
enableCefRemoteDebug=false
enableCefRemoteDebugPort=9222
enableCefTa=false
enableCloudSwitch=true
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enableUnifywebviewTa=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
hideCrashReport=false
host.auto.grab.interval=10
isTransCoding=false
legacyAvatarCacheCleaned=1785489355
logLevel=info
mynotes_persist_language_set="1, 24, 3, 9, 2, 34, 4, 0, 12, 6, 7, 14, 8"
mynotes_persist_offline_mode_enabled=true
newMeetingWithVideo=true
noSandbox=false
playSoundForNewMessage=false
scaleFactor=1.5
shareBarTopMargin=0
shortcut_as_global_ShortcutID_Screenshot=false
shortcut_as_global_ShortcutID_ScreenshotIncludeChatWindow=false
shortcut_as_global_ShortcutID_ShowHideFloatingMeetingControls=true
showEmbeddedAic=false
showOneTimePTAICTipHubble=false
showOneTimeQAMostUpvoteHubble=true
showOneTimeQueriesOptionTip=true
showOneTimeSmartRecognitionCoackMark=false
showOneTimeTranslationUpSellTip=false
showSystemTitlebar=false
speaker_volume=255
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
systemDockMargin=0
timeFormat12HoursEnable=true
translationFreeTrialTipShowTime=0
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=magnus@nfrontventures.com
waylandDesktopNotifications=false
webview.debug.enable=false
xwayland=true

[AS]
showframewindow=true

[CodeSnippet]
lastCodeType=0
wrapMode=0

[chat.recent]
recentlast.session=

[zoom_new_im]
is_landscape_mode=true
main_frame_pixel_pos_narrow="376,600"
main_frame_pixel_pos_wide="1422,902"
