# yazi.toml
[manager]
show_hidden = true

[[plugin.prepend_previewers]]
name = "*.md"
run = "glow"

# [[plugin.prepend_previewers]]
# name = "*/"
# run = "eza-preview"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
